### ISSUE TITLE
More details on the Longest6 benchmark

### ISSUE THREAD

**Issue by SmashChen** [OpenDriveLab/ThinkTwice#10]
Hi authors, thank you for your excellent work!

We would like to cite ThinkTwice as a comparison method, but we evaluated our approach on the Longest6 benchmark. We noticed that you only conducted a single evaluation in your paper. We attempted to run your ckpt model, which you provided in this repository, on the Longest6 benchmark. However, we encountered a challenge as your model demands significant computing resources, which our team cannot afford.

Therefore, we would like to inquire whether you have conducted multiple evaluations on the Longest6 benchmark or if you could offer us some advice on how to proceed.

**Comment by jiaxiaosong1002** [comment]
Thanks for your interests. Howeve, due to limited bandwidth and computational power, we do not have plans do that recently. If you have any new results, you are welcomed to post here and I would like to give an update of the repo.
