### ISSUE TITLE
_get_3d_bbs

### ISSUE THREAD

**Issue by a1wj1** [OpenDriveLab/ThinkTwice#11]
Hi，When collecting data, does the function _get_3d_bbs(self, lidar=None, max_distance=50) obtain vehicles within the range of the ego camera or all vehicles in the world? If it is the former, I don't seem to have written any relevant filtering functions in the code?

**Comment by jiaxiaosong1002** [comment]
No. Please check these related functions all by yourself since I do not use 3d_bbs related function in the final.
