### ISSUE TITLE
The versions of the nvidia gpu, driver, cuda, cudnn? 

### ISSUE THREAD

**Issue by lsrrrrrrrrr** [OpenDriveLab/ThinkTwice#15]
I am trying to start the carla 0.9.10 docker on the gpu 3090 (driver 460.27). However, the 9.10 docker fails to start because the driver is too new. Could you please tell these parameters when conducting the think-twice experiments?

**Comment by jiaxiaosong1002** [comment]
Hi,  ThinTwice has been tested across multiple types of devices including RTX 3090 and nvidia drive 460.  I have not observed any specific requirements for CARLA.

BTW, CARLA might have problems when under the root user, you may want to try to avoid that by creating a new non-root user.

**Comment by lsrrrrrrrrr** [comment]
Many thanks
