### ISSUE TITLE
How to set parameters of transform.py?

### ISSUE THREAD

**Issue by xanhug** [OpenDriveLab/ThinkTwice#20]
Thanks for your amazing work!
If I want to use a single RGB camera and set the resolution to a smaller size, for example, changing it from the default 1600x900 to 900x256, do I need to make corresponding modifications to the parameters in the
```
open_loop_training/code/datasets/pipelines/transform.py
```
file? How should I modify it? Alternatively, if the settings in transform.py for 1600x900 would cause issues at the 900x256 resolution, can I skip this transformation process altogether?

**Comment by xanhug** [comment]
Like these codes:
```
LIDAR2IMG = {
    "rgb_front":np.array([[800.0, 214.35935394, 0.0, -1200.0], [450.0, 0.0, -214.35935394, -139.10161515000004], [1.0, 0.0, 0.0, -1.5], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_left":np.array([[214.35935394, -800.0, 0.0, -240.0], [0.0, -450.0, -214.35935394, 400.89838484999996], [0.0, -1.0, 0.0, -0.3], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_right":np.array([[-214.35935394, 800.0, 0.0, -240.0], [0.0, 450.0, -214.35935394, 400.89838484999996], [0.0, 1.0, 0.0, -0.3], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_back":np.array([[-800.0, -214.35935394, 0.0, -1280.0], [-450.0, 0.0, -214.35935394, -184.10161515000007], [-1.0, 0.0, 0.0, -1.6], [0.0, 0.0, 0.0, 1.0]])
}
```
I can understand that these probably are transformation matrices set based on the original resolution of 1600x900. However, it's not clear whether I should adjust these parameters if I want to change the camera input to 900x256, and if so, how to adjust them.

**Comment by xanhug** [comment]
I have noted that there is a file named "camera_calibration/calculate_distortion_parameters.py", is it could be used for generate parameters for codes below?
```
## Precompute the following matrice to speed
LIDAR2UNREAL = {
    "rgb_front": np.array([[1.0, 0.0, -0.0, -1.5], [0.0, 1.0, 0.0, 0.0], [-0.0, 0.0, 1.0, -2.5], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_back":np.array([[-1.0, -0.0, 0.0, -1.6], [0.0, -1.0, 0.0, -0.0], [0.0, 0.0, 1.0, -2.5], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_left":np.array([[0.0, -1.0, 0.0, -0.3], [1.0, 0.0, -0.0, -0.0], [0.0, 0.0, 1.0, -2.5], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_right":np.array([[0.0, 1.0, -0.0, -0.3], [-1.0, -0.0, 0.0, 0.0], [0.0, 0.0, 1.0, -2.5], [0.0, 0.0, 0.0, 1.0]])
}     

unreal2cam = np.array([[0,1,0,0], [0,0,-1,0], [1,0,0,0], [0,0,0,1]])
LIDAR2CAM = {
    "rgb_front": np.array([ [0.0, 1.0, 0.0, 0.0] , [0.0, 0.0, -1.0, 2.5] , [1.0, 0.0, 0.0, -1.5] , [0.0, 0.0, 0.0, 1.0] ]),
    "rgb_back": np.array([ [0.0, -1.0, 0.0, 0.0] , [0.0, 0.0, -1.0, 2.5] , [-1.0, 0.0, 0.0, -1.6] , [0.0, 0.0, 0.0, 1.0] ]),
    "rgb_left": np.array([ [1.0, 0.0, 0.0, 0.0] , [0.0, 0.0, -1.0, 2.5] , [0.0, -1.0, 0.0, -0.3] , [0.0, 0.0, 0.0, 1.0] ]),
    "rgb_right": np.array([ [-1.0, 0.0, 0.0, 0.0] , [0.0, 0.0, -1.0, 2.5] , [0.0, 1.0, 0.0, -0.3] , [0.0, 0.0, 0.0, 1.0] ]),
}


UNDISTORT_LIDAR2IMG = {
    "rgb_front":np.array([[788.25758876, 304.14395142, 0.0, -1182.38638314], [449.78972161, 0.0, -221.49429321, -120.94884939000008], [1.0, 0.0, 0.0, -1.5], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_left":np.array([[304.14395142, -788.25758876, 0.0, -236.47727662799997], [0.0, -449.78972161, -221.49429321, 418.79881654199994], [0.0, -1.0, 0.0, -0.3], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_right":np.array([[-304.14395142, 788.25758876, 0.0, -236.47727662799997], [0.0, 449.78972161, -221.49429321, 418.79881654199994], [0.0, 1.0, 0.0, -0.3], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_back":np.array([[-788.25758876, -304.14395142, 0.0, -1261.2121420160001], [-449.78972161, 0.0, -221.49429321, -165.9278215510001], [-1.0, 0.0, 0.0, -1.6], [0.0, 0.0, 0.0, 1.0]])
}

LIDAR2IMG = {
    "rgb_front":np.array([[800.0, 214.35935394, 0.0, -1200.0], [450.0, 0.0, -214.35935394, -139.10161515000004], [1.0, 0.0, 0.0, -1.5], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_left":np.array([[214.35935394, -800.0, 0.0, -240.0], [0.0, -450.0, -214.35935394, 400.89838484999996], [0.0, -1.0, 0.0, -0.3], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_right":np.array([[-214.35935394, 800.0, 0.0, -240.0], [0.0, 450.0, -214.35935394, 400.89838484999996], [0.0, 1.0, 0.0, -0.3], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_back":np.array([[-800.0, -214.35935394, 0.0, -1280.0], [-450.0, 0.0, -214.35935394, -184.10161515000007], [-1.0, 0.0, 0.0, -1.6], [0.0, 0.0, 0.0, 1.0]])
}

mtx = np.array([[214.35935394, 0, 800,],[0, 214.35935394, 450],[0, 0, 1]])
dist = np.array([[ 0.00888296, -0.00130899,  0.00012061, -0.00338673,  0.00028834]])
newcameramtx = np.array([[304.14395142,   0,         788.25758876,],
[  0,        221.49429321, 449.78972161,],
[  0,           0,           1,        ],])
CAM_INTRINSIC = {
    "rgb_front": mtx,
    "rgb_back": mtx,
    "rgb_left": mtx,
    "rgb_right": mtx,
}
CAM_DIST= {
    "rgb_front": dist,
    "rgb_back": dist,
    "rgb_left": dist,
    "rgb_right": dist,
}
```
It seems this file can obtain ```mtx``` and ```dist```, but how to obtain ```UNDISTORT_LIDAR2IMG```, ```LIDAR2IMG```, and ```newcameramtx```?

**Comment by xanhug** [comment]
Sorry, I just noticed there is an explanation about ```Calibrations for Different Camera Settings``` on the homepage. I will take a look at it first.

**Comment by jiaxiaosong1002** [comment]
@xanhug Hi, Thanks for your interests.  You might want to read docs in https://github.com/OpenDriveLab/ThinkTwice/tree/main/camera_calibration very carefully, where it demonstrates how to conduct calibration and obtain **dist** matrix.  You might want to learn some knowledge about the distortion of the camera to obtain **newcameramtx**.

However, you could choose to not to conduct undistortion which has limited influence by setting **undistort**  to False.

Besides, as for the change of image resolution, you need to ida_aug_conf (you might need to read the code carefully to understand the augmentation) and the network structure of semantic segmentation network.

Thanks

**Comment by xanhug** [comment]
> @xanhug Hi, Thanks for your interests. You might want to read docs in https://github.com/OpenDriveLab/ThinkTwice/tree/main/camera_calibration very carefully, where it demonstrates how to conduct calibration and obtain **dist** matrix. You might want to learn some knowledge about the distortion of the camera to obtain **newcameramtx**.
> 
> However, you could choose to not to conduct undistortion which has limited influence by setting **undistort** to False.
> 
> Besides, as for the change of image resolution, you need to ida_aug_conf (you might need to read the code carefully to understand the augmentation) and the network structure of semantic segmentation network.
> 
> Thanks

Thanks for your help!
