### ISSUE TITLE
About collect images for calibration.

### ISSUE THREAD

**Issue by xanhug** [OpenDriveLab/ThinkTwice#21]
Hello,
I followed the instructions in ```https://github.com/OpenDriveLab/ThinkTwice/blob/main/camera_calibration/README.md``` and spent several days installing UE4 and Carla. However, when I run ```collect_data_for_calibration.py```, I found that there is no calibration checkerboard in the scene, and the camera perspective does not change. Each frame collected is the same, which cannot be used to calculate distortion parameters with ```calculate_distortion_parameters.py```. 
Could you please provide any suggestions about this situation?
![2024-04-11 13-59-42 的屏幕截图](https://github.com/OpenDriveLab/ThinkTwice/assets/109917206/cb65ebaa-2753-4325-b8a9-928472007f0d)
Additionally, I originally planned to change the camera resolution to 900x256, FOV to 100, front_camera position to ```x=1.3,y=0,z=2.5``` and set ```undistort``` to False, so I don't need to calculate distortion parameters. But there are still some parameters in the transformation matrices that I don't know how to set.

Regarding LIDAR2IMG:
```
LIDAR2IMG = {
    "rgb_front":np.array([[800.0, 214.35935394, 0.0, -1200.0], [450.0, 0.0, -214.35935394, -139.10161515000004], [1.0, 0.0, 0.0, -1.5], [0.0, 0.0, 0.0, 1.0]]),
```

I can see that 800 and 450 are half of the original width 1600 and height 900, and 214.359 corresponds to parameters that can be directly calculated from the image resolution and FOV. After changing the camera settings, this should be changed to 377.594. 

The value of 1200 seems to be related to the camera position, so I still can make a guess about what value should be set for this parameter after changing the camera settings, But I don't know what 139.1016 represents. Therefore, I plan to follow the instructions in ```https://github.com/OpenDriveLab/ThinkTwice/blob/main/camera_calibration/README.md``` to see if it can be calculated by calculate_distortion_parameters.py. However, it seems that there are some problems with the process of collecting images for calibration, which is a bit confusing.

Before possible reply, I will continue to try to solve this problem by myself. If I can solve it successfully, I will close this issue on my own.

**Comment by xanhug** [comment]
Current progress: I directly extracted the compressed files downloaded from IBISCape into the map folder, instead of creating a separate folder within the map folder to store them. Now I can see the calibration board.

![2024-04-11 15-24-43 的屏幕截图](https://github.com/OpenDriveLab/ThinkTwice/assets/109917206/2d625daf-2fe0-4ed5-9fab-721ac23e6865)

**Comment by xanhug** [comment]
Now I have collected some images for calibration and obtained some parameters by running ```calculate_distortion_parameters.py```, but these parameters seem to have nothing to do with 139.1016?

```
Camera matrix : 

[[214.28235796   0.         799.5       ]
 [  0.         214.14580484 449.5       ]
 [  0.           0.           1.        ]]
Distortion Matrix : 

[[ 2.98099705e-03 -4.35741787e-03 -5.61294835e-05  1.27164886e-05
   1.80059518e-03]]
rvecs : 

(array([[0.22166708],
       [0.23211306],
       [1.58715942]]), array([[0.20972128],
       [0.20671492],
       [1.57471855]]), array([[0.10820797],
       [0.10391412],
       [1.57302881]]), array([[0.50355373],
       [0.48164285],
       [1.50607193]]), array([[0.45873178],
       [0.45762182],
       [1.52581263]]), array([[0.45941141],
       [0.4598727 ],
       [1.52925688]]), array([[0.23872499],
       [0.2616931 ],
       [1.55377912]]), array([[0.45415101],
       [0.44368763],
       [1.53894023]]), array([[0.42452736],
       [0.40566571],
       [1.55872336]]), array([[0.2716295 ],
       [0.28624505],
       [1.58581533]]), array([[0.46011214],
       [0.45866348],
       [1.52386996]]), array([[0.08822307],
       [0.08204556],
       [1.57440487]]), array([[0.00347659],
       [0.03479309],
       [0.00905184]]), array([[0.56930725],
       [0.55490375],
       [1.49517161]]), array([[0.46209434],
       [0.46135466],
       [1.53002564]]), array([[0.19148223],
       [0.18293333],
       [1.57392301]]), array([[0.45955071],
       [0.45793221],
       [1.52471733]]), array([[0.45750716],
       [0.4553597 ],
       [1.52393647]]), array([[0.39585859],
       [0.38174277],
       [1.55457805]]), array([[0.33984159],
       [0.33644849],
       [1.55513569]]), array([[0.10041518],
       [0.09533827],
       [1.57324022]]), array([[0.00378244],
       [0.0888063 ],
       [0.00631415]]), array([[0.23874479],
       [0.2573771 ],
       [1.59453126]]), array([[0.44493193],
       [0.42638195],
       [1.55320535]]), array([[0.36492549],
       [0.358147  ],
       [1.5518794 ]]), array([[0.45911729],
       [0.45845451],
       [1.52741744]]), array([[-0.0466223 ],
       [ 0.05257099],
       [-1.56246822]]), array([[-0.04492518],
       [ 0.33337589],
       [-0.00070372]]), array([[0.00424974],
       [0.00491133],
       [0.01047056]]))
tvecs : 

(array([[ 6.59723144],
       [-4.77955409],
       [ 9.6155787 ]]), array([[ 6.23746009],
       [-4.95289208],
       [ 9.62410831]]), array([[ 4.72545169],
       [-5.01703479],
       [ 9.46942248]]), array([[ 9.7733353 ],
       [-5.18042499],
       [10.18032002]]), array([[ 9.51692199],
       [-4.98669711],
       [ 8.62480518]]), array([[ 9.53951498],
       [-4.9755155 ],
       [ 8.85589948]]), array([[ 5.98607525],
       [-5.0324915 ],
       [13.68420973]]), array([[ 9.42421348],
       [-4.95611648],
       [ 8.21378837]]), array([[ 9.07502163],
       [-4.95155019],
       [ 8.31267258]]), array([[ 7.35116272],
       [-4.70289733],
       [ 9.36909196]]), array([[ 9.50337616],
       [-4.98920092],
       [ 8.37361719]]), array([[ 4.44395759],
       [-5.00953886],
       [ 9.36904114]]), array([[-2.34885378],
       [-5.05964229],
       [ 9.56202647]]), array([[10.86401171],
       [-5.07950019],
       [ 8.08573514]]), array([[ 9.58901652],
       [-4.96930508],
       [ 8.93467486]]), array([[ 5.90826339],
       [-4.99996169],
       [ 9.67476568]]), array([[ 9.50968227],
       [-4.98894112],
       [ 8.49963576]]), array([[ 9.46067274],
       [-4.98651146],
       [ 8.28380494]]), array([[ 8.7098112],
       [-4.9658785],
       [ 8.5301649]]), array([[ 7.99445368],
       [-4.95371473],
       [ 8.92081057]]), array([[ 4.61540717],
       [-5.01409643],
       [ 9.40557943]]), array([[-1.75666834],
       [-5.04612606],
       [ 9.8806514 ]]), array([[ 6.95741384],
       [-4.66148217],
       [ 9.56343023]]), array([[ 9.30779252],
       [-4.94145645],
       [ 8.20729119]]), array([[ 8.31617567],
       [-4.96286955],
       [ 8.76270472]]), array([[ 9.52611465],
       [-4.98191613],
       [ 8.74144602]]), array([[-2.08250646],
       [ 0.94791493],
       [ 9.75200973]]), array([[ 0.32376455],
       [-4.93061337],
       [16.35661429]]), array([[-2.66707133],
       [-5.07063039],
       [ 9.3831467 ]]))

Process finished with exit code 0

```


So, could you please tell me what is the parameter 139.1016 here?

```
LIDAR2IMG = {
    "rgb_front":np.array([[800.0, 214.35935394, 0.0, -1200.0], [450.0, 0.0, -214.35935394, -139.10161515000004], [1.0, 0.0, 0.0, -1.5], [0.0, 0.0, 0.0, 1.0]]),
```

 What does it mean? If modify the RGB camera configuration as mentioned above and set undistort to False, do I need to change this parameter? If I don't change it, will it have a significant impact? Because in this case, I really don't know how to modify this parameter.

**Comment by jiaxiaosong1002** [comment]
@xanhug   Hi,  LIDAR2IMG is a mapping from ego coordinate system to image cooridnate system:  it seems that you has not considered the extrinsics (the position of the camera)?

If you set undistort as False, as in [the data loading part](https://github.com/OpenDriveLab/DriveAdapter/blob/4d480bef06073786c1844757e7734b1bff1ff443/open_loop_training/code/datasets/pipelines/transform.py#L93C1-L94C), it will use the conversion matrix without considering Distortion matrx.  As a result, you do not need to conduct calibration at all (much more simple).  All you need is to get the intrinsics and extrinsics matrix (you could use CARLA api in https://carla.readthedocs.io/en/latest/tuto_G_pedestrian_bones/#camera-geometry) and obtain the LiDAR2Img.

I think the calibration would not influence a lot especially with small fov.

**Comment by xanhug** [comment]
> @xanhug Hi, LIDAR2IMG is a mapping from ego coordinate system to image cooridnate system: it seems that you has not considered the extrinsics (the position of the camera)?
> 
> If you set undistort as False, as in [the data loading part](https://github.com/OpenDriveLab/DriveAdapter/blob/4d480bef06073786c1844757e7734b1bff1ff443/open_loop_training/code/datasets/pipelines/transform.py#L93C1-L94C), it will use the conversion matrix without considering Distortion matrx. As a result, you do not need to conduct calibration at all (much more simple). All you need is to get the intrinsics and extrinsics matrix (you could use CARLA api in https://carla.readthedocs.io/en/latest/tuto_G_pedestrian_bones/#camera-geometry) and obtain the LiDAR2Img.
> 
> I think the calibration would not influence a lot especially with small fov.

Thanks a lot.
